In [1]:
from mxnet import nd #导入ndarry库

# 数据操作
## 创建

In [2]:
x = nd.arange(12)#创建行向量 打印出来显示一维数组 
x 


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape #获取NDArry实例的形状

(12,)

In [4]:
x.size #获取元素总数

12

In [5]:
X = x.reshape((3,4)) #三行四列
# X = x.reshape((3,-1)) 
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [6]:
nd.zeros((2,3,4)) # nd.ones((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [7]:
Y = nd.array([[2,1,4,3],[1,2,3,4,],[4,3,2,1]])
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [8]:
nd.random.normal(0,1,shape=(3,4))
#每个元素随机采样于均值为0、标准差为1的正态分布


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

## operator
### 按元素计算
X+Y,X*Y,X/Y...

In [9]:
Y.exp() #按元素做指数运算


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

### 矩阵操作

In [10]:
nd.dot(X,Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [11]:
nd.concat(X,Y,dim=0),nd.concat(X,Y,dim=1)
#矩阵的联结(concatenate)，其中dim规定联结的维度，0行1列

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [12]:
X == Y #条件判断式，相当于&&


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [13]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [14]:
X.norm().asscalar()
#通过asscalar函数将结果变换为Python中的标量（好像是浮点数）。本例中X的L2范数结果同上例一样是单元素nd矩阵，但是最后结果变成了标量

22.494442

## 广播机制
先适当复制(一般为整行整列地复制)元素，使的两个矩阵相同，再按照元素运算。

In [15]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [16]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

## 索引（index）
1. 代表了元素的位置
2. （每个维度地索引）从0起逐一递增
3. 左闭右开

In [17]:
X[1:3] #只是对行索引，维度之间用逗号分隔，后边可以省略


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [18]:
X[1,2] = 9
X #访问单个元素地位置并给该元素赋值


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [19]:
X[1] = 12 
X #给所有行索引为1的元素复制 可记为 X[1:2,:] = 12


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

## 运算的内存开销
`id()`可以显示出实例的位置，从而看出运算结果是否指向新的内存
前面的所有例子，对每个操作新开内存存储运算结果。

In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

False

如果想指定结果写入特定内存，可以使用索引来进行替换操作。
下例实际上是为`X + Y`开了临时内存之后又复制Z到对应的内存。

In [21]:
Z = Y.zeros_like() # 创建一个和Y形状相同但元素全为0的矩阵
before = id(Z) # 取个地址
Z[:] = X + Y #属于赋值，所以不会
id(Z) == before

True

避免临时内存消耗：
1. 使用运算符全名函数中的`out`参数,可以直接指定结果存储的内存。
2. 如果X的值在之后的程序中不会复用，我们也可以用`X[:] = X + Y`or`X += Y`来减少内存开销（可以理解为逐一改变X的值）

In [22]:
nd.elemwise_add(X,Y,out=Z)
id(Z) == before

True

## NDArry和Numpy相互变换
通过`array`和`asnumpy`令数据在两个格式之间相互变换

In [23]:
import numpy as np
P = np.ones((2,3))
D = nd.array(P) #把np矩阵变为nd矩阵用的是变化后的类型的包
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [24]:
D.asnumpy() #注意这里是输出D的np矩阵形式，并不是把D变成np矩阵

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# 自动求梯度
梯度gradient

* `MXNet`提供`autograd` 模块来自动化求导；
* `MXNet`的`autograd`模块可以对一般的命令式程序进行求导；
* `MXNet`的运行模式包括训练模式和预测模式，我们可以通过`autograd.istraining()`来判断运行模式；

In [25]:
from mxnet import autograd,nd

## 简单例子
对函数$y=2x^Tx$求关于列向量x的梯度。
1. 首先创建变量x并初始化：

In [26]:
x = nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

2. 调用`attach_grad`函数来申请存储梯度所需要的内存

In [27]:
x.attach_grad()

3. 定义有关变量x的函数，并调用`record`函数来要求`MXNet`记录与梯度有关的计算。（默认条件下不会记录梯度计算）

In [28]:
with autograd.record():
    y = 2 * nd.dot(x.T,x) #注意是矩阵乘法，y是一个标量

4. 调用`backward`函数自动求梯度
* 如果y是矩阵，即y不是一个标量，`MXNet`将默认先对y中元素求和得到新的变量，再求该变量有关x的梯度。

In [29]:
y.backward()

函数$y = 2x^Tx$关于$x$的梯度应该为$4x$，验证梯度正确：
* `assert`：断言函数，测试表达式，用于判断程序是否会出现异常。如果把`assert`删掉会发现输出变成`Flase`.
* 用法：
```
assert expression [, arguments]
```
expression：表示要检测的表达式;
arguments：给出报错提示;
```ruby
>>> assert 1==2，'不相等'
  File "<stdin>", line 1  # 报出异常，并给出提示信息
    assert 1==2，'不相等'
>>> assert 1==1，'不相等'  # 继续往下执行
# 类似于：
if not expression： # 判断表达式是否征程
    raise AssertionError(arguments)  # 抛出异常
```

In [30]:
assert(x.grad - 4 * x).norm().asscalar() == 0 #norm是一个求范数的函数，我也不知道啥意思（）
x.grad # 输出矩阵的梯度（？）不太懂


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

## 训练模式与预测模式
`autograd`会将运行模式从预测模式转为训练模式，可以通过调用`is_training`函数查看(因为在有些情况下同一个模型在训练模式和预测模式下的行为并不相同)

In [31]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


## 对Python控制流求梯度
使用MXNet的一个便利之处是，即使函数的计算过程包含了Python的控制流（如条件控制循环控制），我们也有可能对变量求梯度。


比方说，下面程序包含这两种控制流，不过循环迭代次数以及if语句的执行都取决于a的值。

In [32]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0: # sum函数可以对列表、各种数据类型（可混合）以及参数（用range（x,y））求和
        c = B
    else :
        c = 100 * b 
    return c

### `sum`用法补充：
标准形式：`sum(iterable[, start])`；

`lterable`:可迭代对象（列表list、元组tuple、集合set、字典dictionary...）

`start`:指定相加的参数，如果没有这个值，默认是0.

也就是说`sum()`结果=可迭代对象里边数的和（字典是key值相加） + start的值，如果没写就默认是0
```ruby
>>> sum = sum([1,2,3],5)          #in list +start
11
>>> sum = sum((1,2,3))            #in tuple
6
>>> sum = sum({1,2,3})            #in set
6
>>> sum = sum({1:5,2:6,3:7})      #in dictionary key
6
>>>sum = sum([1,2,3])             # in list
6
1
2
```

以及，给定任意输入a，输出必然是f(a) = x * a的形式，其中标量系数x的值取决于输入a。由于c = f(a)有关a的梯度为x，且值为c/a，我们可以如下验证对本例中控制流求梯度结果的正确性。

像之前一样使用`record`函数计算，并调用`backward`函数求梯度。

In [33]:
a = nd.random.normal(shape=1) 
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()
a.grad == c/a


[1.]
<NDArray 1 @cpu(0)>

### normal()分析：
在本例中`random.normal()`是生成一个随机的正态分布函数，其中`normal`表正态。

`loc:`正态分布的均值，对应这个分布的中心，代表$\mu$;

`scale`:正态分布的标准差，对应分布的宽度，越大越矮胖，越小越高瘦，代表$\sigma$;

`size`:你输入数据的shape;

# 查阅文档
## 查找模块里所有的函数和类
```ruby
from mxnet import nd
print(dir(nd.random))#查找模块中的函数
```
我们可以忽略由__开头和结尾的特别对象函数或者由_开头的内部函数
## 查找特定函数或类的使用
了解某个函数或类的具体用法：
```ruby
help(nd.ones_like)
```
显示在额外窗口：
```ruby
nd.random.uniform?
```
额外显示该函数的实现代码：
```ruby
nd.random.uniform??
```
在官网上，点击顶部“API”可以查阅各个前端语言的接口